### ISSUE TITLE
Cant build web demo

### ISSUE THREAD

**Issue by zvory** [elspru/spel#2]
Error is:

```
sadeq@sadeq-ThinkPad-T450s:~/Documents/Projects/spel/src/web$ ./build.sh 
Error: Cannot find module './subType' from '/home/sadeq/Documents/Projects/spel/src/class'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by zvory** [comment]
New missing file
```
sadeq@sadeq-ThinkPad-T450s:~/Documents/Projects/spel/src/web$ ./build.sh 
Error: Cannot find module 'colors' from '/home/sadeq/Documents/Projects/spel/src/lang'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by elspru** [comment]
Okay I've added npm add colors to the README.md,
also mentioned to do the npm installs in the src/ directory.
and added my node_modules folder to hopefully simplify the process for future users.

**Comment by elspru** [comment]
assuming latest inclusion fixed issues.
