### ISSUE TITLE
Cannot run test suite

### ISSUE THREAD

**Issue by zvory** [elspru/spel#3]
Error is 

#### Through Node:
```
sadeq@sadeq-ThinkPad-T450s:~/Documents/Projects/spel/src$ node test.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'tape'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/sadeq/Documents/Projects/spel/src/test.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```
#### Through ./ :
```
sadeq@sadeq-ThinkPad-T450s:~/Documents/Projects/spel/src$ ./test.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'tape'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/sadeq/Documents/Projects/spel/src/test.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by zvory** [comment]
New missing file
```
sadeq@sadeq-ThinkPad-T450s:~/Documents/Projects/spel/src/web$ ./build.sh 
Error: Cannot find module 'colors' from '/home/sadeq/Documents/Projects/spel/src/lang'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by zvory** [comment]
This is with ```tape``` installed through npm.

**Comment by elspru** [comment]
make sure your node_modules folder is in the src/ directory
otherwise you'd have to do npm install -g npm

**Comment by zvory** [comment]
yes, tape and all npm modules i use are installed with -g

**Comment by elspru** [comment]
I've added my node_modules directory to the git repo, so can pull that, see if it helps.

**Comment by elspru** [comment]
assuming lates inclusion fixed issues
